#!/usr/bin/env zsh

# zshrc.d/36-p10k-theme.zsh
# Purpose: Powerlevel10k Gruvbox 風格色彩覆寫
#
# 在 p10k 本體載入後覆寫預設配色，統一跨機器的視覺風格。
# 色彩數值基於 256-color terminal palette，與 Gruvbox Dark 主題搭配。

# 確認 p10k 已載入才進行覆寫
(( $+functions[p10k] )) || return

# ── 全域底色 / 前景色 ──
typeset -g POWERLEVEL9K_BACKGROUND=236
typeset -g POWERLEVEL9K_FOREGROUND=223

# ── OS icon ──
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=220

# ── Directory ──
typeset -g POWERLEVEL9K_DIR_FOREGROUND=214
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=214
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=220
typeset -g POWERLEVEL9K_DIR_BACKGROUND=236

# ── VCS / Git ──
typeset -g POWERLEVEL9K_VCS_FOREGROUND=178
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=178
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=214
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=220
typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=203
typeset -g POWERLEVEL9K_VCS_BACKGROUND=236

# ── Status ──
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=142
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=203
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=203
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=203

# ── Prompt character ──
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND=220
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND=203
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_FOREGROUND=178
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_FOREGROUND=203

# ── Command execution time / Time ──
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=136
typeset -g POWERLEVEL9K_TIME_FOREGROUND=136

# ── Context (username / hostname) ──
typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=220
typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=203
typeset -g POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND=214
typeset -g POWERLEVEL9K_CONTEXT_BACKGROUND=236

# ── Python / Node / 版本管理工具 ──
typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=178
typeset -g POWERLEVEL9K_PYENV_FOREGROUND=178
typeset -g POWERLEVEL9K_PYTHON_FOREGROUND=178
typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND=214
typeset -g POWERLEVEL9K_NVM_FOREGROUND=214

# ── Kubernetes / AWS / Terraform ──
typeset -g POWERLEVEL9K_KUBECONTEXT_FOREGROUND=220
typeset -g POWERLEVEL9K_AWS_FOREGROUND=214
typeset -g POWERLEVEL9K_TERRAFORM_FOREGROUND=178

# ── 模組背景色（保持深色，比黃色色塊更清爽）──
typeset -g POWERLEVEL9K_TIME_BACKGROUND=236
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=236
typeset -g POWERLEVEL9K_STATUS_BACKGROUND=236
typeset -g POWERLEVEL9K_CONTEXT_BACKGROUND=236
