"""Build the wizard's animation frames into hooks/hero-cells.ts.

Usage: python3 tools/make-frames.py
Reads tools/hero-20.txt (one character per pixel, see PALETTE) and writes
idle (orb breathing), cast (staff raised, sparkles) and hurt (smoke puff)
frames as half-block Raster cells. Transparent pixels take the terminal's
default colour.
"""
import base64
import pathlib
import struct

ROOT = pathlib.Path(__file__).resolve().parent.parent
SIZE = 20

PALETTE = {
    '.': None,
    'B': (30, 144, 255), 'b': (120, 200, 255),
    'S': (247, 196, 140), 's': (232, 150, 60),
    'K': (20, 20, 20), 'W': (255, 255, 255), 'P': (255, 105, 160),
    'R': (229, 57, 53), 'r': (150, 25, 25),
    'U': (40, 120, 235), 'Y': (255, 210, 60),
    'L': (240, 240, 240), 'G': (170, 170, 170),
    'N': (150, 85, 35), 'n': (95, 50, 20),
    'H': (217, 119, 87), 'h': (160, 78, 55),
    'V': (98, 78, 190), 'v': (64, 48, 135),
    'C': (150, 240, 255), 'c': (60, 170, 225), 'D': (30, 100, 150),
    'E': (238, 238, 248), 'e': (185, 185, 210),
    'O': (40, 32, 64),
    'g': (120, 120, 135), 'm': (190, 190, 205),
}

UPPER_HALF = 0x2580
LOWER_HALF = 0x2584
SPACE = 0x20
DEFAULT = 0x01000000  # the terminal's own colour

# The orb and staff occupy the columns left of the hat.
ORB_COLUMNS = range(0, 7)


def load_base():
    rows = [r for r in (ROOT / 'tools' / 'hero-20.txt').read_text().split('\n') if r.strip()]
    assert len(rows) == SIZE and all(len(r) == SIZE for r in rows)
    return [list(r) for r in rows]


def copy(grid):
    return [row[:] for row in grid]


def recolor_orb(grid, mapping):
    out = copy(grid)
    for y in range(SIZE):
        for x in ORB_COLUMNS:
            out[y][x] = mapping.get(out[y][x], out[y][x])
    return out


STAFF_PIXELS = {'c', 'C', 'n'}


def raise_staff(grid):
    """Lift the orb and staff one row; the hand stays where it holds the staff."""
    out = copy(grid)
    for y in range(SIZE):
        for x in ORB_COLUMNS:
            if grid[y][x] in STAFF_PIXELS:
                out[y][x] = '.'
    for y in range(1, SIZE):
        for x in ORB_COLUMNS:
            if grid[y][x] in STAFF_PIXELS:
                out[y - 1][x] = grid[y][x]
    return out


def dot(grid, points, ch):
    out = copy(grid)
    for x, y in points:
        out[y][x] = ch
    return out


def encode(grid):
    def color(ch):
        rgb = PALETTE[ch]
        return None if rgb is None else (rgb[0] << 16) | (rgb[1] << 8) | rgb[2]

    words = []
    for row in range(SIZE // 2):
        for col in range(SIZE):
            top, bottom = color(grid[2 * row][col]), color(grid[2 * row + 1][col])
            if top is None and bottom is None:
                words += [SPACE, DEFAULT, DEFAULT]
            elif top is None:
                # A default foreground is the text colour, not see-through: draw the lower half.
                words += [LOWER_HALF, bottom, DEFAULT]
            elif bottom is None:
                words += [UPPER_HALF, top, DEFAULT]
            else:
                words += [UPPER_HALF, top, bottom]
    return base64.b64encode(struct.pack(f'<{len(words)}I', *words)).decode()


def frames():
    base = load_base()
    bright = recolor_orb(base, {'c': 'C', 'C': 'W'})
    dim = recolor_orb(base, {'c': 'D', 'C': 'c'})
    idle = [base, bright, base, dim]

    raised = recolor_orb(raise_staff(base), {'c': 'C', 'C': 'W'})
    cast = [
        dot(raised, [(0, 0), (6, 1), (0, 5), (6, 4)], 'Y'),
        dot(raised, [(5, 0), (0, 2), (6, 3), (1, 6)], 'W'),
    ]

    hurt_base = dim
    hurt = [
        dot(hurt_base, [(16, 1), (17, 1), (16, 2)], 'g'),
        dot(dot(hurt_base, [(15, 0), (16, 0), (17, 0), (16, 1), (17, 1), (18, 1)], 'm'),
            [(17, 2), (18, 2), (16, 2)], 'g'),
        dot(hurt_base, [(17, 0), (19, 1), (18, 3)], 'g'),
    ]
    return {'idle': idle, 'cast': cast, 'hurt': hurt}


def main():
    built = frames()
    lines = [
        '// Generated by tools/make-frames.py from tools/hero-20.txt; do not edit by hand.',
        'export const HERO_FRAMES = {',
        f'  columns: {SIZE},',
        f'  rows: {SIZE // 2},',
    ]
    for mood, grids in built.items():
        lines.append(f'  {mood}: [')
        lines += [f"    '{encode(grid)}'," for grid in grids]
        lines.append('  ],')
    lines.append('}')
    out = ROOT / 'hooks' / 'hero-cells.ts'
    out.write_text('\n'.join(lines) + '\n')
    print(f'{out}: ' + ', '.join(f'{mood} {len(g)}' for mood, g in built.items()))

    # Previews for a person to eyeball, outside the mod.
    try:
        from PIL import Image
    except ImportError:
        return
    sheet = Image.new('RGBA', (SIZE * 12 * 9 + 8 * 8, SIZE * 12), (30, 30, 40, 255))
    x = 0
    for grids in built.values():
        for grid in grids:
            im = Image.new('RGBA', (SIZE, SIZE), (0, 0, 0, 0))
            for yy, row in enumerate(grid):
                for xx, ch in enumerate(row):
                    if PALETTE[ch]:
                        im.putpixel((xx, yy), PALETTE[ch] + (255,))
            sheet.alpha_composite(im.resize((SIZE * 12, SIZE * 12), Image.NEAREST), (x, 0))
            x += SIZE * 12 + 8
    sheet.save(ROOT / 'tools' / 'frames-preview.png')


if __name__ == '__main__':
    main()
