"""Turn a pixel-art PNG into hooks/hero-cells.ts (half-block Raster cells).

Usage: python3 tools/make-hero.py <png> [size]
The PNG is scaled to size x size (default 20) with nearest-neighbour, so draw it
at 20x20 or an exact multiple (320x320). Transparent pixels take the terminal's
default colour.
"""
import base64
import pathlib
import struct
import sys

from PIL import Image

UPPER_HALF = 0x2580
LOWER_HALF = 0x2584
SPACE = 0x20
DEFAULT = 0x01000000  # the terminal's own colour

src = pathlib.Path(sys.argv[1])
size = int(sys.argv[2]) if len(sys.argv) > 2 else 20
im = Image.open(src).convert('RGBA').resize((size, size), Image.NEAREST)
px = im.load()


def color(p):
    r, g, b, a = p
    return None if a < 128 else (r << 16) | (g << 8) | b


words = []
for row in range(size // 2):
    for col in range(size):
        top, bottom = color(px[col, 2 * row]), color(px[col, 2 * row + 1])
        if top is None and bottom is None:
            words += [SPACE, DEFAULT, DEFAULT]
        elif top is None:
            # A default foreground is the text colour, not see-through: draw the lower half instead.
            words += [LOWER_HALF, bottom, DEFAULT]
        elif bottom is None:
            words += [UPPER_HALF, top, DEFAULT]
        else:
            words += [UPPER_HALF, top, bottom]

cells = base64.b64encode(struct.pack(f'<{len(words)}I', *words)).decode()
out = pathlib.Path(__file__).resolve().parent.parent / 'hooks' / 'hero-cells.ts'
out.write_text(
    f'// Generated by tools/make-hero.py from {src.name}; do not edit by hand.\n'
    f'export const HERO_CELLS = {{\n  columns: {size},\n  rows: {size // 2},\n'
    f"  cells: '{cells}',\n}}\n"
)
print(f'{out}: {size} columns x {size // 2} rows')
